SwapiApi/Models/ErrorViewModel.cs
using System;

namespace SwapiApi.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SwapiApi/Models/PlanetResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SwapiApi.Models
{
    public class PlanetResponse
    {
      

        public int count { get; set; }
        public string next { get; set; }
        public object previous { get; set; }
        public List<Result> results { get; set; }


        public class Result
        {
            public string name { get; set; }
            public string rotation_period { get; set; }
            public string orbital_period { get; set; }
            public string diameter { get; set; }
            public string climate { get; set; }
            public string gravity { get; set; }
            public string terrain { get; set; }
            public string surface_water { get; set; }
            public string population { get; set; }
            public string[] residents { get; set; }
            public string[] films { get; set; }
            public DateTime created { get; set; }
            public DateTime edited { get; set; }
            public string url { get; set; }
        }

        
    }
}

SwapiApi/Controllers/SwapiController.cs
using Microsoft.AspNetCore.Mvc;
using SwapiApi.Models;
using SwapiApi.Services;
using System.Threading.Tasks;

namespace SwapiApi.Controllers
{
    public class SwapiController : Controller
    {
        private readonly IPlanetClient _planetClient;

        public SwapiController(IPlanetClient planetClient)
        {
            _planetClient = planetClient;           
        }

        public async Task<IActionResult> ChangePage(string url)
        {
            var UrlStrippedToPageInfo = url.Substring(url.Length - 15);
            var model = new PlanetResponse();
            var response = await _planetClient.GetPlanetInfo(UrlStrippedToPageInfo);
            model.results = response.results;
            model.previous = response.previous;
            model.next = response.next;
            return View("GetAllPlanets",model);
        }
        public async Task<IActionResult> GetAllPlanets()
        {

            var model = new PlanetResponse();
            var response = await _planetClient.GetPlanetInfo();
            model.results = response.results;
            model.next = response.next;
            model.previous = response.previous;
            return View(model);
        }

    }
}

SwapiApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SwapiApi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SwapiApi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SwapiApi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SwapiApi/Views/Swapi/GetAllPlanets.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model PlanetResponse

@foreach (var planet in Model.results)
{ 
    <p>@planet.name - @planet.climate</p>
    
}
<a asp-controller="Swapi" asp-action="ChangePage" asp-route-url="@Model.previous">Previous</a>
<a asp-controller="Swapi" asp-action="ChangePage" asp-route-url="@Model.next">Next</a>